// <auto-generated />
using System;
using LaytonTemple.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTemple.Migrations
{
    [DbContext(typeof(ApptContext))]
    partial class ApptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaytonTemple.Models.AvailableTimes", b =>
                {
                    b.Property<string>("TimeSlot")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeSlot");

                    b.ToTable("AvailableTimes");
                });

            modelBuilder.Entity("LaytonTemple.Models.GroupInfo", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("groupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("timeslot")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupID");

                    b.ToTable("GroupInfo");
                });

            modelBuilder.Entity("LaytonTemple.Models.ViewModels.GroupView", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("groupinfoGroupID")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupID");

                    b.HasIndex("TimeSlot");

                    b.HasIndex("groupinfoGroupID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("LaytonTemple.Models.ViewModels.GroupView", b =>
                {
                    b.HasOne("LaytonTemple.Models.AvailableTimes", "timeslot")
                        .WithMany()
                        .HasForeignKey("TimeSlot");

                    b.HasOne("LaytonTemple.Models.GroupInfo", "groupinfo")
                        .WithMany()
                        .HasForeignKey("groupinfoGroupID");
                });
#pragma warning restore 612, 618
        }
    }
}
